name: CI - Integration and E2E Tests

on: [pull_request]

jobs:
  run-int-e2e-tests:
    name: Run Integration and E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: projectdb

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npx prisma generate --schema ./src/shared/infra/database/prisma/schema.prisma
        env:
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/projectdb?schema=public'

      - run: npm run test:int
        env:
          PORT: 3333
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/projectdb?schema=public'

      - run: npm run test:e2e
        env:
          PORT: 3333
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/projectdb?schema=public'
